---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demoapp
  labels:
    app: demoapp
spec:
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      imagePullSecrets:
      - name: nexus-auth
      # volumes:
      containers:
        - name: demoapp
          image: "__REGISTRY_URL__/__REGISTRY_USER__/demoapp:1.0"
          ports:
            - name: http
              containerPort: 80
  replicas: 1
